// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb2Ht4cSMlU5mo16enZpicWQ4dPBCSdKc',
    appId: '1:481325909049:web:da42222b38cab0fe6479e8',
    messagingSenderId: '481325909049',
    projectId: 'findit-telu',
    authDomain: 'findit-telu.firebaseapp.com',
    storageBucket: 'findit-telu.firebasestorage.app',
    measurementId: 'G-C7LG40W4FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkUIm9uCsBn-4Bp53nZdNRXdv_z8YqdS4',
    appId: '1:481325909049:android:8b2b4e7296d5075c6479e8',
    messagingSenderId: '481325909049',
    projectId: 'findit-telu',
    storageBucket: 'findit-telu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDrIP66udG9cfa9SbOG9ZGap7baYos7w',
    appId: '1:481325909049:ios:6fa26784909295656479e8',
    messagingSenderId: '481325909049',
    projectId: 'findit-telu',
    storageBucket: 'findit-telu.firebasestorage.app',
    iosBundleId: 'com.example.finditTelu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDrIP66udG9cfa9SbOG9ZGap7baYos7w',
    appId: '1:481325909049:ios:6fa26784909295656479e8',
    messagingSenderId: '481325909049',
    projectId: 'findit-telu',
    storageBucket: 'findit-telu.firebasestorage.app',
    iosBundleId: 'com.example.finditTelu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb2Ht4cSMlU5mo16enZpicWQ4dPBCSdKc',
    appId: '1:481325909049:web:9bd01456bf04435a6479e8',
    messagingSenderId: '481325909049',
    projectId: 'findit-telu',
    authDomain: 'findit-telu.firebaseapp.com',
    storageBucket: 'findit-telu.firebasestorage.app',
    measurementId: 'G-2B3EZ2F43L',
  );
}
